import type { Metadata } from "next";
import { PageSchema, SiteFooter, SiteHeader } from "../site-shell";

export const metadata: Metadata = {
  title: "Drinks Brand Marketing Agency UK",
  description: "Consumer demand, trade stories, launch campaigns and stockist journeys for UK drinks brands.",
  alternates: { canonical: "/drinks-brands" },
  openGraph: { title: "Drinks Brand Marketing Agency UK | No Quiet Nights", description: "Build consumer pull, strengthen the trade story and turn discovery into demand.", url: "/drinks-brands", type: "website" },
};

const serviceSchema = { "@context":"https://schema.org", "@type":"Service", name:"Drinks Brand Marketing", serviceType:"Drinks brand marketing agency services", provider:{"@type":"Organization","@id":"https://no-quiet-nights.vercel.app/#organization",name:"No Quiet Nights"}, areaServed:{"@type":"Country",name:"United Kingdom"}, audience:{"@type":"Audience",audienceType:"Drinks brands and beverage companies"}, url:"https://no-quiet-nights.vercel.app/drinks-brands" };

export default function DrinksBrandsPage() {
  return <><SiteHeader/><main id="main-content">
    <PageSchema name="Drinks Brand Marketing Agency UK" description="Consumer demand, trade stories, launch campaigns and stockist journeys for UK drinks brands." path="/drinks-brands"/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/>
    <section className="drinks-hero page-top"><div className="drinks-hero-copy"><p className="eyebrow">Drinks brand growth</p><h1>Become the drink people ask for by <em>name.</em></h1><p>Build consumer pull, strengthen the trade story and move people from first discovery to first serve, stockist search and repeat purchase.</p><a className="button button-ink" href="/start?type=drinks-brand">Plan a demand campaign <span>↗</span></a></div><div className="bottle-stage"><div className="bottle-label"><span>NQN / 01</span><strong>FIRST<br/>SERVE</strong><small>Demand, bottled properly</small></div><img alt="A cocktail served at a bar" src="https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1400&q=82"/><p>THE LIQUID IS ONLY THE BEGINNING</p></div></section>
    <section className="liquid-route section-pad"><span className="route-index">01 / ROUTE TO MARKET</span><h2>A great liquid is not<br/>a route to <em>market.</em></h2><p>Quality matters once somebody tastes it. Before that, the brand has to be understood, remembered, stocked, recommended and ordered.</p><div className="liquid-wordmark" aria-hidden="true">TASTE ≠ DEMAND</div></section>
    <section className="three-audiences section-pad"><p className="eyebrow light">One brand. Three decisions.</p><h2>Who has to<br/><em>believe?</em></h2><div className="audience-triangle"><article className="drinker"><span>01</span><h3>The drinker</h3><p>Why should I notice it, try it and order it again?</p></article><article className="buyer"><span>02</span><h3>The buyer</h3><p>Why will it earn space, sell through and suit the customer?</p></article><article className="bartender"><span>03</span><h3>The bartender</h3><p>Why should I recommend it, serve it correctly and remember the story?</p></article><div><b>NQN</b><small>One demand story</small></div></div></section>
    <section className="first-serve section-pad"><div className="first-serve-head"><p className="eyebrow">The demand journey</p><h2>First scroll.<br/><em>First serve.</em></h2></div><ol><li><span>01</span><strong>Position</strong><p>Say what the brand owns.</p></li><li><span>02</span><strong>Recognise</strong><p>Build a distinctive memory.</p></li><li><span>03</span><strong>Try</strong><p>Create a credible reason for the first taste.</p></li><li><span>04</span><strong>Find</strong><p>Make the stockist or serve discoverable.</p></li><li><span>05</span><strong>Repeat</strong><p>Give demand somewhere to compound.</p></li></ol></section>
    <section className="drinks-capabilities"><div className="drinks-cap-photo"><img alt="Cocktail glowing under warm bar light" src="https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1400&q=82"/></div><div className="drinks-cap-copy"><p className="eyebrow light">Bottle + bar</p><h2>Demand work that<br/><em>lands.</em></h2><div><p><span>01</span>Brand + campaign positioning<i>↗</i></p><p><span>02</span>Social content systems<i>↗</i></p><p><span>03</span>Paid consumer demand<i>↗</i></p><p><span>04</span>Launch landing pages<i>↗</i></p><p><span>05</span>Stockist + trade journeys<i>↗</i></p><p><span>06</span>Email + SMS<i>↗</i></p><p><span>07</span>Sampling + activation<i>↗</i></p><p><span>08</span>Bartender toolkits<i>↗</i></p></div></div></section>
    <section className="drinks-engagement section-pad"><div><span>KEEP POURING</span><h3>Social plans from<br/><b>£165/month</b></h3><p>Consistent professional content for early-stage and established drinks brands.</p><a href="/pricing">See monthly plans ↗</a></div><div><span>MAKE A SPLASH</span><h3>Scoped launch<br/><b>campaigns</b></h3><p>Product launches, creator programmes, activations, stockist campaigns and larger creative jobs.</p><a href="/start?type=drinks-brand">Brief the launch ↗</a></div></section>
  </main><SiteFooter/></>;
}