import type { Metadata } from "next";
import Link from "next/link";
import ServiceHeader from "../services/service-header";

const siteUrl = "https://www.noquietnights.co.uk";
const url = `${siteUrl}/restaurant-google-ads-agency`;

export const metadata: Metadata = {
  title: "Restaurant Google Ads Agency UK | NO QUIET NIGHTS",
  description: "Google Ads management for UK restaurants, from high-intent local search to private dining and launch demand. Restaurant marketing plans from £495/month.",
  alternates: { canonical: url },
  openGraph: { title: "Restaurant Google Ads Agency UK | NO QUIET NIGHTS", description: "Google Ads for restaurants built around bookings, enquiries and measurable demand.", url, type: "website" },
};

const faqs = [
  ["Do Google Ads work for restaurants?", "They can work when people are already searching with strong local or occasion intent and the landing page, booking journey and economics are strong enough to convert that demand."],
  ["How much does restaurant Google Ads management cost?", "NO QUIET NIGHTS Demand is £495 per month and includes one managed paid channel, Google Ads or Meta Ads, alongside local visibility, landing-page support, conversion tracking and CRM. Media spend is separate."],
  ["What searches can restaurants advertise against?", "Useful themes can include cuisine, location, private dining, group bookings, events, occasions and branded demand. The campaign structure should follow the commercial opportunity rather than chase every possible keyword."],
  ["Do you guarantee bookings from Google Ads?", "No. We do not guarantee covers, revenue or a fixed return. We build the campaign around measurable intent, track the evidence available and optimise according to commercial performance."],
];

const schema = { "@context":"https://schema.org", "@graph":[
  { "@type":"Service", name:"Restaurant Google Ads Agency UK", serviceType:"Restaurant Google Ads management", url, provider:{"@type":"Organization",name:"NO QUIET NIGHTS",url:siteUrl}, areaServed:{"@type":"Country",name:"United Kingdom"}, offers:{"@type":"Offer",priceCurrency:"GBP",price:"495",description:"Demand plan from £495/month. Advertising media spend is separate."}},
  { "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:siteUrl},{"@type":"ListItem",position:2,name:"Restaurant Google Ads Agency",item:url}]},
  { "@type":"FAQPage", mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}
]};

export default function Page(){return <><ServiceHeader/><main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="service-detail-hero"><div className="service-detail-copy"><p className="eyebrow">Restaurant Google Ads agency UK</p><h1>Capture demand when diners are already searching.</h1><strong>Google Ads should meet high-intent restaurant searches with a reason to choose you and a booking path that does not leak.</strong><p>We plan restaurant search campaigns around real buying moments: where to eat, private dining, group bookings, launches, occasions and local demand. The job is not clicks. The job is qualified demand that has somewhere useful to go.</p><div className="service-hero-actions"><Link className="button button-ink" href="/start?type=restaurant">Discuss Google Ads ↗</Link><Link className="text-link" href="/pricing">See Demand from £495 →</Link></div></div><figure className="service-detail-image"><img src="/images/stock/restaurant-12-table-setting-menu.jpg" alt="Restaurant table setting and menu ready for guests"/><figcaption>Stock hospitality image</figcaption></figure></section>
<section className="proof-principle section-pad"><p className="eyebrow">The short answer</p><h2>Buy the search only if the <em>journey can convert it.</em></h2><p>Google Ads can place a restaurant in front of people showing strong intent. But paying for visibility into a slow website, weak proposition or confusing booking flow just buys traffic into a leak. We connect campaign, landing page, tracking and follow-up.</p></section>
<section className="service-work section-pad"><div className="service-section-head"><p className="eyebrow">What we can build</p><h2>Search campaigns with a <em>commercial job.</em></h2></div><div className="work-list"><article><span>01</span><div><h3>Local dining demand</h3><p>Capture high-intent cuisine and location searches where the restaurant has a genuine reason to compete.</p></div></article><article><span>02</span><div><h3>Private dining and groups</h3><p>Route higher-value searches to dedicated pages built around room, capacity, occasion and enquiry.</p></div></article><article><span>03</span><div><h3>Launch and event demand</h3><p>Support openings, seasonal services and ticketed moments when search intent is already forming.</p></div></article><article><span>04</span><div><h3>Tracking and optimisation</h3><p>Measure calls, forms, booking actions and other conversion signals available, then cut waste and concentrate spend.</p></div></article></div></section>
<section className="service-outcomes section-pad"><div className="service-section-head"><p className="eyebrow">What should we measure?</p><h2>Not impressions. Intent moving towards action.</h2></div><div className="outcome-grid"><article><span>01</span><h2>Qualified search terms and useful click-through.</h2></article><article><span>02</span><h2>Booking actions, calls and enquiries where tracking allows.</h2></article><article><span>03</span><h2>Cost per useful action, not just cost per click.</h2></article><article><span>04</span><h2>Which services, occasions and audiences produce the strongest economics.</h2></article></div></section>
<section className="service-proof section-pad"><div className="service-section-head"><p className="eyebrow">Pricing</p><h2>Restaurant Google Ads management sits inside Demand from £495/month.</h2></div><div className="proof-grid"><article><span>£495 / month</span><h3>Demand</h3><p>Visibility plus one managed paid channel, landing-page support, conversion tracking, email/CRM and monthly growth review. Ad spend is separate.</p></article><article><span>£1,000 / month</span><h3>Full House</h3><p>Includes both Google and Meta alongside SEO growth, CRM automation, retargeting, win-back, website optimisation and advanced reporting.</p></article><article><span>Important</span><h3>Media spend is separate</h3><p>Your advertising budget is not hidden inside the management fee. That keeps the economics easier to read.</p></article></div></section>
<section className="playbook-band section-pad"><p className="eyebrow">Related buyer guides</p><h2>Research before you spend.</h2><p><Link href="/insights/google-ads-vs-meta-ads-restaurants">Google Ads vs Meta Ads for restaurants →</Link></p><p><Link href="/insights/how-much-should-a-restaurant-spend-on-marketing">How much should a restaurant spend on marketing? →</Link></p><p><Link href="/restaurant-marketing-packages">Restaurant marketing packages →</Link></p></section>
<section className="section-pad"><p className="eyebrow">FAQs</p><h2>Restaurant Google Ads questions</h2>{faqs.map(([q,a])=><article key={q}><h3>{q}</h3><p>{a}</p></article>)}</section>
<section className="service-next section-pad"><p className="eyebrow">Next step</p><h2>What are people already searching for that should end at <em>your table?</em></h2><p>Bring us the opportunity. We will tell you whether Google Ads is actually the sensible starting point.</p><div><Link className="button button-cream" href="/start?type=restaurant">Tell us the quiet bit ↗</Link><Link className="text-link" href="/pricing">Compare plans →</Link></div></section>
</main></>}
