import type { Metadata } from "next";
import { PageSchema, SiteFooter, SiteHeader } from "../site-shell";

export const metadata: Metadata = {
  title: "Proof and Measurement",
  description: "How No Quiet Nights measures hospitality marketing—real baselines, defined periods and evidence that survives the monthly meeting.",
  alternates: { canonical: "/work" },
  openGraph: { title: "Proof and Measurement | No Quiet Nights", description: "Real baselines, defined periods and evidence that survives the monthly meeting.", url: "/work", type: "website" },
};

export default function WorkPage() {
  return <><SiteHeader/><main id="main-content">
    <PageSchema name="Proof and Measurement" description="How No Quiet Nights measures hospitality marketing using real baselines, defined periods and commercial evidence." path="/work"/>
    <section className="work-hero page-top"><p className="eyebrow light">Work + proof</p><h1>Proof should survive the <em>monthly meeting.</em></h1><p>Commercial proof needs a real baseline, real work and enough time to measure honestly. Until a client case is verified and approved, we show the method—not projections dressed up as history.</p><a className="button button-cream" href="/start">Bring us a measurable brief <span>↗</span></a><div className="work-stamp"><span>NO</span><b>BORROWED</b><strong>LOGOS</strong></div></section>
    <section className="proof-ledger section-pad"><div className="proof-ledger-head"><p className="eyebrow">The case ledger</p><h2>Every number<br/>needs a <em>receipt.</em></h2><p>No magic percentage floating above a stock photo. Every published case must carry the context that makes it useful.</p></div><div className="proof-requirements"><article><span>01</span><h3>Pressure point</h3><p>The exact service, audience or revenue line at risk.</p><i>REQUIRED</i></article><article><span>02</span><h3>Baseline</h3><p>What was happening before any work began.</p><i>REQUIRED</i></article><article><span>03</span><h3>Intervention</h3><p>The campaign, creative and journey we changed.</p><i>REQUIRED</i></article><article><span>04</span><h3>Fixed period</h3><p>A start, finish and fair comparison window.</p><i>REQUIRED</i></article><article><span>05</span><h3>Outcome</h3><p>Booking, enquiry, revenue or demand movement.</p><i>REQUIRED</i></article><article><span>06</span><h3>Source</h3><p>The system or dataset behind the claim.</p><i>REQUIRED</i></article></div></section>
    <section className="metric-wall"><div className="metric-wall-title"><p className="eyebrow light">What gets measured</p><h2>Different trade.<br/><em>Different truth.</em></h2></div><article><span>RESTAURANTS</span><h3>Target-service covers</h3><p>Direct bookings · private dining · guest acquisition cost · repeat visits</p></article><article><span>PUBS + BARS</span><h3>Session performance</h3><p>Tickets · food covers · private hire · event response · repeat attendance</p></article><article><span>DRINKS BRANDS</span><h3>Qualified demand</h3><p>Trade enquiries · stockist searches · trial actions · repeat purchase where data exists</p></article></section>
    <section className="testimony-standard section-pad"><div><p className="eyebrow">Client voices</p><h2>A quote is evidence<br/>only when it is <em>theirs.</em></h2></div><blockquote><span>“</span>Approved client comments will appear here with a real name, role, business and permission—never a made-up founder from a made-up venue.<span>”</span></blockquote><p>This module is intentionally ready for verified testimonials. Publishing invented praise would weaken the trust the page is designed to create.</p></section>
    <section className="work-behind section-pad"><p className="eyebrow light">The craft behind the number</p><h2>The result is the headline.<br/><em>The work made it possible.</em></h2><div><span><b>01</b>Campaign creative</span><span><b>02</b>Conversion pages</span><span><b>03</b>Paid variants</span><span><b>04</b>Content systems</span><span><b>05</b>Email sequences</span><span><b>06</b>Booking journeys</span><span><b>07</b>Event assets</span><span><b>08</b>Measurement views</span></div><a className="button button-cream" href="/services">Explore the growth system <span>↗</span></a></section>
  </main><SiteFooter/></>;
}