import type { Metadata } from "next";
import styles from "../restaurant-marketing-agency-cost-uk/blog.module.css";

export const metadata: Metadata = {
  title: "How Much Should a Restaurant Spend on Marketing in the UK? | NO QUIET NIGHTS",
  description: "A practical UK restaurant marketing budget guide: how to set spend from unused capacity, margins, channel needs and commercial targets instead of copying generic percentages.",
  alternates: { canonical: "/insights/how-much-should-restaurant-spend-on-marketing-uk" },
};

const faqs=[
["What percentage of revenue should a restaurant spend on marketing?","There is no universal percentage that fits every restaurant. Stage of growth, margin, unused capacity, local competition, launch requirements and existing customer demand all change the answer."],
["How should a small restaurant set a marketing budget?","Start with the specific commercial gap, estimate its realistic value, decide which channels are capable of addressing it, and set a test budget that the business can measure and afford."],
["Should ad spend be included in the marketing budget?","Yes, but separate management fees, creative production, software and media spend so you can see what each part of the budget is doing."],
];
const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:"How Much Should a Restaurant Spend on Marketing in the UK?",datePublished:"2026-08-29",dateModified:"2026-08-29",inLanguage:"en-GB",author:{"@type":"Organization",name:"NO QUIET NIGHTS"},publisher:{"@type":"Organization",name:"NO QUIET NIGHTS"},mainEntityOfPage:"https://no-quiet-nights.vercel.app/insights/how-much-should-restaurant-spend-on-marketing-uk",about:["restaurant marketing budget","restaurant marketing spend UK","hospitality marketing budget"]},{"@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
export default function Page(){return <div className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><main>
<section className={styles.hero}><div className={styles.breadcrumbs}>Home / Insights / Restaurants / Marketing budget</div><p className={styles.eyebrow}>NO QUIET NIGHTS / BUYER GUIDE</p><h1>How much should a restaurant spend on marketing in the UK?</h1><p className={styles.dek}>A useful budget starts with the commercial gap, not a generic percentage copied from another restaurant.</p><div className={styles.meta}><span>Updated 29 August 2026</span><span>Restaurant marketing</span><span>Budget planning</span></div></section>
<section className={styles.answer}><div className={styles.answerLabel}>The short answer</div><h2>Spend enough to address a defined trading problem, but not so much that the economics stop making sense.</h2><p>There is no single correct restaurant marketing percentage. A new opening, a mature neighbourhood restaurant and a multi-site group have different needs. Work backwards from unused capacity, margin, customer value, competitive pressure and the channels required to solve the problem.</p><div className={styles.answerActions}><a className={styles.primary} href="/pricing">See plans from £165 →</a><a className={styles.secondary} href="/start">Tell us what needs to be busier ↗</a></div></section>
<div className={styles.layout}><article className={styles.article}>
<h2>Why generic marketing percentages can mislead restaurants</h2><p>A percentage of revenue can be a useful guardrail, but it ignores the shape of the problem. A restaurant with a full weekend and empty weekday lunches should not budget the same way as a new venue trying to create awareness from zero.</p>
<h2>Start with unused commercial capacity</h2><p>Suppose a restaurant has room for 15 more covers every Wednesday and average guest spend is £35. That is £525 of potential revenue per service, or roughly £2,100 across four Wednesdays before costs and margin.</p><p className={styles.note}>Illustrative example only. This is not a forecast or guaranteed return.</p><p>The purpose of the calculation is not to justify spending £2,100. It is to understand the size of the opportunity before deciding whether £200, £500 or £1,000 of marketing activity could be rational.</p>
<h2>Separate the budget into jobs</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Budget line</th><th>What it pays for</th></tr></thead><tbody><tr><td>Management</td><td>Strategy, campaign planning, optimisation and reporting</td></tr><tr><td>Media</td><td>Money paid to Google, Meta or other platforms</td></tr><tr><td>Content production</td><td>Photography, video, design and editing</td></tr><tr><td>SEO / website</td><td>Discovery and conversion infrastructure</td></tr><tr><td>CRM / retention</td><td>Email, SMS, customer capture and repeat-visit systems</td></tr></tbody></table></div>
<div className={styles.callout}><p className={styles.eyebrow}>The commercial test</p><h3>What would have to become busier for this budget to be justified?</h3><p>If nobody can answer that clearly, the budget is not yet tied closely enough to the business.</p></div>
<h2>When to spend more</h2><p>Higher investment can make sense around a launch, new location, highly competitive market, substantial unused capacity, a major private-hire opportunity or a growth plan requiring several channels to work together.</p>
<h2>When to spend less</h2><p>Spend less when the bottleneck is operational rather than marketing, the venue cannot fulfil more demand, one narrow intervention is enough, or measurement is too weak to know what the additional budget would accomplish.</p>
<h2>A sensible budget should be able to answer four questions</h2><ol><li>What commercial problem are we funding?</li><li>Which channel or system is most likely to change it?</li><li>How will we measure whether it worked?</li><li>What would make us increase, reduce or stop the spend?</li></ol>
<div className={styles.take}><p className={styles.eyebrow}>The NO QUIET NIGHTS take</p><h2>Choose the smallest budget capable of producing a useful commercial answer.</h2><p>Then scale when the numbers do.</p></div>
<h2 id="faq">Frequently asked questions</h2>{faqs.map(([q,a])=><div className={styles.faq} key={q}><h3>{q}</h3><p>{a}</p></div>)}
<h2>Sources and methodology</h2><p>Current UK restaurant marketing guides publish widely varying budget percentages and monthly figures. Because these are often supplier estimates rather than universal industry rules, this guide deliberately avoids presenting one percentage as fact and instead uses a capacity-and-return framework.</p>
</article><aside className={styles.sidebar}><strong>Restaurant buyer guides</strong><a href="/insights/restaurant-marketing-agency-cost-uk">Agency cost</a><a href="/insights/restaurant-seo-cost-uk">SEO cost</a><a href="/pricing">Pricing</a></aside></div>
<section className={styles.final}><p className={styles.eyebrow}>YOUR TURN</p><h2>What are you paying to fix?</h2><p>Bring us the commercial gap. We will point to the smallest sensible starting point.</p><a href="/start">Tell us the quiet bit ↗</a></section>
</main></div>}
