import type { Metadata } from "next";
import { PageSchema, SiteFooter, SiteHeader } from "../site-shell";

export const metadata: Metadata = {
  title: "Pub and Bar Marketing Agency UK",
  description: "Local marketing for UK pubs and bars—quiet sessions, events, food trade, private hire and repeat visits.",
  alternates: { canonical: "/pubs-bars" },
  openGraph: { title: "Pub and Bar Marketing Agency UK | No Quiet Nights", description: "Build local demand around the sessions that need it.", url: "/pubs-bars", type: "website" },
};

const serviceSchema = { "@context":"https://schema.org", "@type":"Service", name:"Pub and Bar Marketing", serviceType:"Pub and bar marketing agency services", provider:{"@type":"Organization","@id":"https://no-quiet-nights.vercel.app/#organization",name:"No Quiet Nights"}, areaServed:{"@type":"Country",name:"United Kingdom"}, audience:{"@type":"Audience",audienceType:"Pubs, bars and hospitality operators"}, url:"https://no-quiet-nights.vercel.app/pubs-bars" };

export default function PubsBarsPage() {
  return <><SiteHeader/><main id="main-content">
    <PageSchema name="Pub and Bar Marketing Agency UK" description="Local marketing for UK pubs and bars, from quiet sessions to events, food trade, private hire and repeat visits." path="/pubs-bars"/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/>
    <section className="pub-hero page-top"><img alt="Guests talking in a warm pub and bar setting" src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1800&q=82"/><div className="pub-hero-overlay"></div><div className="pub-sign"><span>NO QUIET</span><strong>NIGHTS</strong><small>LOCAL DEMAND · SERVED DAILY</small></div><div className="pub-hero-copy"><p className="eyebrow light">Pubs + bars</p><h1>A packed Saturday does not pay for an empty <em>Tuesday.</em></h1><p>We build local demand around the sessions that need it—from roasts and live sport to cocktails, private hire and the ordinary visit that becomes a habit.</p><a className="button button-cream" href="/start?type=pub-bar">Fix a quiet session <span>↗</span></a></div></section>
    <section className="sofa-section section-pad"><p className="eyebrow">The reason to leave home</p><h2>People do not leave the sofa<br/>for <em>content.</em></h2><div><p>They leave for a reason. The right local audience has to know what is happening, why it is worth coming and how to book before another venue wins the night.</p><blockquote>Not another pint photo.<br/>A reason, timed properly.</blockquote></div></section>
    <section className="weekly-board section-pad"><div className="weekly-board-head"><p className="eyebrow light">Build the week</p><h2>Session by<br/><em>session.</em></h2><span>LIVE TRADING BOARD / UK</span></div><div className="week-rows"><article><b>MON</b><h3>THE QUIET RESET</h3><p>Local ritual · value without cheapening</p><small>CREATE</small></article><article><b>TUE</b><h3>GIVE IT A REASON</h3><p>Quiz · tasting · community night</p><small>CREATE</small></article><article><b>WED</b><h3>MIDWEEK HABIT</h3><p>Food · sport · regulars</p><small>CREATE</small></article><article><b>THU</b><h3>WEEKEND STARTS</h3><p>Drinks occasion · live programme</p><small>CREATE</small></article><article><b>FRI</b><h3>HIGH INTENT</h3><p>Groups · late bookings · walk-ins</p><small>CREATE</small></article><article><b>SAT</b><h3>CAPTURE DEMAND</h3><p>Data · reviews · next visit</p><small>CAPTURE</small></article><article><b>SUN</b><h3>MAKE IT SACRED</h3><p>Roast · families · advance booking</p><small>CREATE</small></article></div></section>
    <section className="pub-reasons"><div className="pub-reasons-photo"><img alt="Friends enjoying a night together around a table" src="https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1400&q=82"/></div><div className="pub-reasons-copy"><p className="eyebrow light">Reasons that travel locally</p><h2>Make tonight<br/><em>specific.</em></h2><ul><li><span>01</span>Food + Sunday trade<i>↗</i></li><li><span>02</span>Live sport<i>↗</i></li><li><span>03</span>Quiz + entertainment<i>↗</i></li><li><span>04</span>Cocktail occasions<i>↗</i></li><li><span>05</span>Private hire<i>↗</i></li><li><span>06</span>Seasonal events<i>↗</i></li><li><span>07</span>Refurbishments + openings<i>↗</i></li><li><span>08</span>Community partnerships<i>↗</i></li></ul></div></section>
    <section className="regulars-loop section-pad"><div><p className="eyebrow">The better metric</p><h2>The first visit fills a seat.<br/><em>The next five build the business.</em></h2></div><div className="loop-track"><span>FIRST VISIT</span><i>→</i><span>REVIEW</span><i>→</i><span>PERMISSION</span><i>→</i><span>NEXT EVENT</span><i>→</i><span>REGULAR</span><i>↺</i></div><p>Capture useful permission, follow up after events, promote the next reason and become part of the customer’s normal week.</p></section>
    <section className="pub-final"><p>LAST ORDERS FOR QUIET NIGHTS</p><h2>Tell us which night<br/>needs <em>work.</em></h2><a className="button button-cream" href="/start?type=pub-bar">Fix my quiet session <span>↗</span></a></section>
  </main><SiteFooter/></>;
}