import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hospitality Marketing Agency Pricing UK | Plans from £165",
  description: "No Quiet Nights hospitality marketing pricing for UK restaurants, pubs and bars. Compare monthly plans from £165 covering social media, local SEO, paid ads and customer follow-up.",
  alternates: { canonical: "/pricing" },
  openGraph: {
    title: "Hospitality Marketing Agency Pricing UK | No Quiet Nights",
    description: "Compare simple monthly hospitality marketing plans from £165 for social media, Google visibility, ads and repeat customers.",
    url: "/pricing",
    type: "website",
  },
};

const siteUrl = "https://www.noquietnights.co.uk";
const plans = [
  { n:"01",name:"Starter",price:"165",title:"Show up like a venue worth visiting.",copy:"For hospitality businesses that need consistent, professional social media without overcomplicating it.",items:["Instagram, Facebook and TikTok","3 planned posts per week","Professional graphic design and video editing","Monthly content calendar","Basic social media plan","Stories 2 to 3 times per week"],cta:"Start with Starter",href:"/start?plan=starter" },
  { n:"02",name:"Visibility",price:"295",title:"Be easier to find. Harder to ignore.",copy:"Help more local people find you on social media, Google and Maps.",items:["Everything in Starter","5 planned posts per week","Full social profile setup and improvements","Google Business Profile improvements","Local SEO setup and ongoing work","Local keyword plan","Google Maps visibility improvements","Review growth plan","Website SEO recommendations","Monthly content and campaign plan","Community management","Stories 3 to 5 times per week","Monthly visibility report"],cta:"Build my visibility",href:"/start?plan=visibility" },
  { n:"03",name:"Demand",price:"495",title:"Turn local attention into bookings and enquiries.",copy:"We run the ads, build the offer and help turn interest into bookings.",items:["Everything in Visibility","Meta ads management","Google Search ads management","Campaign and offer planning","Dedicated campaign landing page","Lead and booking capture setup","Tracking setup","Customer follow-up system","Instant enquiry follow-up","Ads for people who already showed interest","Monthly review of what is working and what to do next","Monthly performance report"],cta:"Build demand",href:"/start?plan=demand" },
  { n:"04",name:"Full House",price:"1,000",title:"Your complete marketing team for growth and repeat business.",copy:"For venues that want one team helping people find them, choose them, book and come back.",items:["Everything in Demand","Full hospitality marketing plan","Offer and campaign calendar","Grow your customer email and SMS list","Email and SMS marketing","Birthday, VIP and win-back campaigns","Repeat-customer automations","Advertising to people who already know you","Website and booking journey improvements","Monthly review of what is working and what to do next","Priority campaign planning"],cta:"Build my Full House plan",href:"/start?plan=full-house" }
];

const schema={"@context":"https://schema.org","@type":"Service",name:"Hospitality Marketing Agency Plans",serviceType:"Hospitality marketing",provider:{"@type":"Organization",name:"No Quiet Nights",url:siteUrl},areaServed:{"@type":"Country",name:"United Kingdom"},offers:plans.map(p=>({"@type":"Offer",name:`${p.name} hospitality marketing plan`,price:p.price,priceCurrency:"GBP",url:`${siteUrl}/pricing#${p.name.toLowerCase().replace(" ","-")}`,description:p.copy}))};

export default function PricingPage(){return <main className="pricing-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="pricing-hero page-top"><p className="eyebrow">Hospitality marketing pricing</p><h1>Simple monthly plans from £165.<br/><em>Grow when you're ready.</em></h1><div className="pricing-hero-aside"><p>Start with what you need now. Add Google visibility, paid ads and customer follow-up when the business is ready for more.</p><a className="button button-ink" href="/start">Find my starting plan <span>↗</span></a></div></section><section id="monthly" className="plan-selector section-pad"><div className="selector-head"><p className="eyebrow">Monthly plans</p><h2>What does hospitality<br/><em>marketing cost?</em></h2><p>Our monthly plans run from £165 to £1,000. Photography, videography and on-site content are priced separately because every venue needs something different.</p></div><div className="selector-list">{plans.map(p=><article id={p.name.toLowerCase().replace(" ","-")} key={p.name} style={{padding:'28px 0'}}><span>{p.n}</span><h2>{p.name} — £{p.price}/month</h2><h3>{p.title}</h3><p>{p.copy}</p><ul>{p.items.map(i=><li key={i}>{i}</li>)}</ul><a className="button button-signal" href={p.href}>{p.cta} ↗</a></article>)}</div></section><section className="playbook-band section-pad"><p className="eyebrow">Comparing agency costs?</p><h2>See what other agencies charge<br/><em>before you decide.</em></h2><p>Our buyer guides explain typical agency fees, ad spend, content costs and the questions worth asking before you sign.</p><p><a href="/insights/restaurant-marketing-agency-cost-uk">Restaurant marketing agency cost UK →</a></p><p><a href="/insights/pub-marketing-agency-cost-uk">Pub marketing agency cost UK →</a></p><p><a href="/insights/drinks-marketing-agency-cost-uk">Drinks marketing agency cost UK →</a></p></section><section className="pricing-final"><span>Not sure which package fits?</span><h2>Start with the problem.<br/><em>Not the biggest plan.</em></h2><p>Tell us what needs to get busier. We will point to the smallest sensible starting point.</p><a className="button button-cream" href="/start">Talk through the options ↗</a></section></main>}
