import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hospitality Marketing Agency Pricing UK | Plans from £165",
  description: "No Quiet Nights hospitality marketing pricing for UK restaurants, pubs and bars. Compare monthly plans from £165 covering social media, local SEO, paid ads, CRM and growth strategy.",
  alternates: { canonical: "/pricing" },
  openGraph: {
    title: "Hospitality Marketing Agency Pricing UK | No Quiet Nights",
    description: "Compare transparent monthly hospitality marketing plans from £165 for visibility, demand and repeat-customer growth.",
    url: "/pricing",
    type: "website",
  },
};

const plans = [
  { n:"01",name:"Starter",price:"165",title:"Show up like a venue worth visiting.",copy:"For hospitality businesses that need consistent, professional social media without overcomplicating it.",items:["Instagram, Facebook and TikTok","3 planned posts per week","Professional graphic design and video editing","Monthly content calendar","Basic social media plan","Stories 2 to 3 times per week"],cta:"Start with Starter",href:"/start?plan=starter" },
  { n:"02",name:"Visibility",price:"295",title:"Be easier to find. Harder to ignore.",copy:"Help more local people find you on social media, Google and Maps.",items:["Everything in Starter","5 planned posts per week","Full social profile setup and improvements","Google Business Profile improvements","Local SEO setup and ongoing work","Local keyword plan","Google Maps visibility improvements","Review growth plan","Website SEO recommendations","Monthly content and campaign plan","Community management","Stories 3 to 5 times per week","Monthly visibility report"],cta:"Build my visibility",href:"/start?plan=visibility" },
  { n:"03",name:"Demand",price:"495",title:"Turn local attention into bookings and enquiries.",copy:"We run the ads, build the offer and help turn interest into bookings.",items:["Everything in Visibility","Meta ads management","Google Search ads management","Campaign and offer planning","Dedicated campaign landing page","Lead and booking capture setup","Tracking setup","Customer follow-up system","Instant enquiry follow-up","Ads for people who already showed interest","Monthly growth review","Monthly performance report"],cta:"Build demand",href:"/start?plan=demand" },
  { n:"04",name:"Full House",price:"1,000",title:"Build the whole customer growth system.",copy:"For venues that want one joined-up marketing plan covering discovery, demand, customer capture and repeat visits.",items:["Everything in Demand","Full hospitality marketing strategy","Offer and campaign calendar","Customer database growth plan","Email and SMS marketing","Birthday, VIP and win-back campaigns","Repeat-customer automations","Retargeting across paid channels","Website and booking journey improvements","Monthly commercial growth review","Priority campaign planning"],cta:"Build my Full House plan",href:"/start?plan=full-house" }
];

const schema={"@context":"https://schema.org","@type":"Service",name:"Hospitality Marketing Agency Plans",serviceType:"Hospitality marketing",provider:{"@type":"Organization",name:"No Quiet Nights",url:"https://no-quiet-nights.vercel.app"},areaServed:{"@type":"Country",name:"United Kingdom"},offers:plans.map(p=>({"@type":"Offer",name:`${p.name} hospitality marketing plan`,price:p.price,priceCurrency:"GBP",url:`https://no-quiet-nights.vercel.app/pricing#${p.name.toLowerCase().replace(" ","-")}`,description:p.copy}))};

export default function PricingPage(){return <main className="pricing-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="pricing-hero page-top"><p className="eyebrow">Hospitality marketing agency pricing UK</p><h1>Hospitality marketing plans from £165/month.<br/><em>Scale when the numbers do.</em></h1><div className="pricing-hero-aside"><p>Compare monthly marketing packages for restaurants, pubs and bars. Start with consistent social media, add local SEO and Google visibility, then layer in paid demand, CRM and repeat-customer marketing when the commercial opportunity justifies it.</p><a className="button button-ink" href="/start">Find my starting plan <span>↗</span></a></div></section><section id="monthly" className="plan-selector section-pad"><div className="selector-head"><p className="eyebrow">Monthly agency packages</p><h2>What does hospitality<br/><em>marketing cost?</em></h2><p>Our own plans run from £165 to £1,000 per month. Photography, videography and on-site content production are scoped separately because the crew, location and deliverables vary.</p></div><div className="selector-list">{plans.map(p=><article id={p.name.toLowerCase().replace(" ","-")} key={p.name} style={{padding:'28px 0'}}><span>{p.n}</span><h2>{p.name} — £{p.price}/month</h2><h3>{p.title}</h3><p>{p.copy}</p><ul>{p.items.map(i=><li key={i}>{i}</li>)}</ul><a className="button button-signal" href={p.href}>{p.cta} ↗</a></article>)}</div></section><section className="playbook-band section-pad"><p className="eyebrow">Comparing agency costs?</p><h2>Our price is one number.<br/><em>Your decision needs context.</em></h2><p>If you are researching typical market rates rather than No Quiet Nights packages, use our buyer guides. They separate agency fees, media spend, production and the commercial questions worth asking before you sign.</p><p><a href="/insights/restaurant-marketing-agency-cost-uk">Restaurant marketing agency cost UK →</a></p><p><a href="/insights/pub-marketing-agency-cost-uk">Pub marketing agency cost UK →</a></p><p><a href="/insights/drinks-marketing-agency-cost-uk">Drinks marketing agency cost UK →</a></p></section><section className="pricing-final"><span>Not sure which package fits?</span><h2>Start with the problem.<br/><em>Not the biggest retainer.</em></h2><p>Tell us what needs to get busier. We will point to the smallest sensible starting point.</p><a className="button button-cream" href="/start">Talk through the numbers ↗</a></section></main>}
